version: '3'
services:
  db:
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      # - /usr/data/volumes/pgdata/etc:/etc/postgresql
      # - /usr/data/volumes/pgdata/log:/var/log/postgresql
      # - /usr/data/volumes/pgdata/data:/var/lib/postgresql/data
      - postgres_data:/var/lib/postgresql/data

  webpacker:
    build: .
    command: bundle exec bin/webpack-dev-server
    volumes:
      - .:/bolt-network-react
    ports:
      - 3035:3035

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/bolt-network-react
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
    external: true
