version: '3'
services:
  db:
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  webpacker:
    build: .
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    command: ./bin/webpack-dev-server
    volumes:
      - .:/bolt-network-react
    ports:
      - 3035:3035

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/bolt-network-react
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpacker

volumes:
  postgres_data:
    external: true
