// Banner Movies Types

export const FETCH_BANNER_MOVIES_BEGIN = 'FETCH_BANNER_MOVIES_BEGIN'

export const FETCH_BANNER_MOVIES_SUCCESS = 'FETCH_BANNER_MOVIES_SUCCESS'

export const FETCH_BANNER_MOVIES_FAILURE = 'FETCH_BANNER_MOVIES_FAILURE'
