// Carousel Movies Types

export const FETCH_CAROUSEL_MOVIES_BEGIN = 'FETCH_CAROUSEL_MOVIES_BEGIN'

export const FETCH_CAROUSEL_MOVIES_SUCCESS = 'FETCH_CAROUSEL_MOVIES_SUCCESS'

export const FETCH_CAROUSEL_MOVIES_FAILURE = 'FETCH_CAROUSEL_MOVIES_FAILURE'
