// Recent Movies Types

export const FETCH_RECENT_MOVIES_BEGIN = 'FETCH_RECENT_MOVIES_BEGIN'

export const FETCH_RECENT_MOVIES_SUCCESS = 'FETCH_RECENT_MOVIES_SUCCESS'

export const FETCH_RECENT_MOVIES_FAILURE = 'FETCH_RECENT_MOVIES_FAILURE'
