// Suggestion Types

export const FETCH_SUGGESTIONS_BEGIN = 'FETCH_SUGGESTIONS_BEGIN'

export const FETCH_SUGGESTIONS_SUCCESS = 'FETCH_SUGGESTIONS_SUCCESS'

export const FETCH_SUGGESTIONS_FAILURE = 'FETCH_SUGGESTIONS_FAILURE'

export const RESET_SUGGESTIONS = 'RESET_SUGGESTIONS'
