export { default as Home } from './Home'
export { default as Genre } from './Genre'
export { default as Movie } from './Movie'
export { default as Recent } from './Recent'
export { default as MyList } from './MyList'
export { default as Search } from './Search'
